# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

shared:
  alpha_vantage_api_key: VUE61XPFAOIAZKQB

development:
  secret_key_base: f684e8139c5cdf2c907cd5fb5fcf7e44886e54c5f9fb685c4cd16139f28ad56c3c53d3d1799dbf6288fd7690d9f2da260716a5034fb17dff198426aac58bf023

test:
  secret_key_base: 8676addc730e6213c9e8ebe6fda4354c957fa515fc3e322c4333fa454d6b473e343397fc07a0e10099b82b407f22644358c7829ad31def58219a3778fd269e38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
